import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "../../../components/theme-provider"
// import { ReactNode } from "react";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '../../i18n/routing';

export const metadata: Metadata = {
  title: "HRPortfolio",
  description: "Generated by rayan",
};



export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = (await import(`@/messages/${locale}.json`)).default;
 return (
    <>
      <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} suppressHydrationWarning>

        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
